apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: tinybankcustomer
  name: tinybankcustomer
  description: A sample microservice catalogued in Backstage.
spec:
  type: service
  lifecycle: production
  owner: guests
  system: core-system
  providesApis:
    - tinybank-customer-api
    